"""The website voice widget, and the pieces it needs.

Lifted out of app/exotel/bridge.py when the Exotel telephony path was
removed. The widget was never Exotel's — it is the "talk to Nikki" console
on heynikki.in — it simply lived in the same file as the carrier bridge and
would have been deleted along with it.

Nothing here talks to a carrier. Audio arrives from a browser over a
websocket, goes to Sarvam for transcription and to Gemini for a reply.
"""

import asyncio
import json
import logging
import os
import re
import time
from typing import Optional

from fastapi import WebSocket

import httpx

from app import knowledge

log = logging.getLogger("nikki")

SARVAM_API_KEY = os.environ.get("SARVAM_API_KEY", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL   = os.environ.get("GEMINI_MODEL", "gemini-flash-lite-latest")
LANGUAGE_NAMES = {"te-IN": "Telugu", "hi-IN": "Hindi", "en-IN": "English"}

def build_outbound_prompt(script: str, first_name: str = None) -> str:
    """System prompt for an outbound campaign call — wraps the campaign's
    script with the language marker and compliance rules. The TRAI
    disclosure ("this call is handled by an automated AI assistant") is
    played as audio BEFORE the conversation starts (see the outbound
    branch in handle_exotel_ws), so this prompt reinforces it rather than
    repeating it every turn — but the AI must never claim to be human if
    asked directly, regardless of what the script says."""
    name_line = f"- The recipient's name is {first_name}, use it naturally.\n" if first_name else ""
    return f"""మీరు ఒక professional Telugu AI voice assistant, ఔట్‌బౌండ్ కాల్ చేస్తున్నారు.
Rules:
__LANGUAGE_RULE__
- SHORT responses (1-2 sentences). Phone call, not chat.
- The caller already heard a disclosure that this call is automated before you started talking — don't repeat that yourself, but if asked directly whether you're human or AI, always say AI assistant, never claim otherwise.
- If the recipient asks to be removed from future calls, sounds unwilling to talk, or asks you to stop, acknowledge respectfully and end the call — do not persist or re-pitch.
{name_line}Your goal for this call:
{script}
"""

async def sarvam_stt(pcm_16k: bytes) -> tuple:
    """Returns (transcript, detected_language_code). language_code="unknown"
    triggers Sarvam's automatic language detection — see the "Live language
    switching" comment block above for why. Detected code falls back to ""
    on any failure; callers should keep the session's previous language in
    that case rather than resetting to a default."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1); wf.setsampwidth(2); wf.setframerate(PIPE_SR)
        wf.writeframes(pcm_16k)

    if not cb.sarvam_stt_breaker.allow_request():
        log.warning("sarvam_stt: circuit OPEN, skipping live call")
        return "", ""

    async with httpx.AsyncClient(timeout=20) as c:
        try:
            r = await c.post("https://api.sarvam.ai/speech-to-text",
                headers={"api-subscription-key": SARVAM_KEY},
                files={"file": ("audio.wav", buf.getvalue(), "audio/wav")},
                data={"language_code":"unknown", "model":"saarika:v2.5"})
        except Exception as e:
            log.error("STT request failed: %s", e)
            cb.sarvam_stt_breaker.record_failure()
            return "", ""
        if r.status_code != 200:
            log.error("STT %s: %s", r.status_code, r.text[:150])
            cb.sarvam_stt_breaker.record_failure()
            return "", ""
        cb.sarvam_stt_breaker.record_success()
        body = r.json()
        return body.get("transcript", "").strip(), body.get("language_code", "")

async def gemini_reply_streaming(history: list, system: str):
    """Streaming variant of gemini_reply — yields COMPLETE SENTENCES as the
    model produces them, instead of returning only once the whole reply is
    finished.

    WHY THIS EXISTS (latency)
    speak_dynamic already pipelines TTS sentence-by-sentence, but it could
    not start until Gemini had finished generating everything. So a
    three-sentence reply meant: wait for all three to generate, THEN start
    synthesising the first. On measured turns the LLM step was a large,
    irreducible-looking block of dead air.

    With streaming, sentence 1 goes to TTS while sentences 2 and 3 are still
    being generated by the model. The caller starts hearing the answer as
    soon as the first sentence exists. On multi-sentence replies this removes
    most of the LLM wait from what the caller actually experiences.

    Yields str (one complete sentence at a time). Falls back to a single
    yield of the full text if streaming is unavailable, so behaviour never
    regresses to worse than before.
    """
    trimmed = history[-(MAX_HISTORY_TURNS * 2):]
    contents = [{"role": "user" if m["role"] == "user" else "model",
                 "parts": [{"text": m["content"]}]} for m in trimmed]
    # streamGenerateContent + alt=sse gives incremental server-sent events.
    url = ("https://generativelanguage.googleapis.com/v1beta/models/"
           "gemini-2.5-flash:streamGenerateContent?alt=sse&key=" + GEMINI_KEY)

    if not cb.gemini_breaker.allow_request():
        log.warning("gemini_reply_streaming: circuit OPEN")
        yield "క్షమించండి, technical issue."
        return

    payload = {
        "system_instruction": {"parts": [{"text": system}]},
        "contents": contents,
        "generationConfig": {
            "maxOutputTokens": 150, "temperature": 0.7,
            # Same reasoning as the non-streaming path: thinking mode leaks
            # the model's reasoning into spoken output and balloons TTS time.
            "thinkingConfig": {"thinkingBudget": 0},
        },
    }

    buffer = ""
    emitted_any = False
    try:
        async with httpx.AsyncClient(timeout=30) as c:
            async with c.stream("POST", url,
                                headers={"Content-Type": "application/json"},
                                json=payload) as r:
                if r.status_code != 200:
                    body = (await r.aread()).decode("utf-8", "replace")[:300]
                    log.error("Gemini stream %s: %s", r.status_code, body)
                    cb.gemini_breaker.record_failure()
                    yield "క్షమించండి, technical issue."
                    return

                async for raw_line in r.aiter_lines():
                    if not raw_line or not raw_line.startswith("data:"):
                        continue
                    chunk = raw_line[5:].strip()
                    if not chunk or chunk == "[DONE]":
                        continue
                    try:
                        obj = json.loads(chunk)
                    except json.JSONDecodeError:
                        continue
                    try:
                        parts = obj["candidates"][0]["content"]["parts"]
                    except (KeyError, IndexError):
                        continue
                    for p in parts:
                        # Skip any thought parts defensively — thinkingBudget 0
                        # should prevent them, but a leaked thought spoken to a
                        # real caller is the exact bug we fixed once already.
                        if p.get("thought"):
                            continue
                        buffer += p.get("text", "")

                    # Emit whole sentences as soon as they're complete.
                    while True:
                        m = re.search(r'[.!?।]\s', buffer)
                        if not m:
                            break
                        sentence, buffer = buffer[:m.end()].strip(), buffer[m.end():]
                        if sentence:
                            emitted_any = True
                            yield sentence

        # whatever's left after the stream closes
        tail = buffer.strip()
        if tail:
            emitted_any = True
            yield tail

        if emitted_any:
            cb.gemini_breaker.record_success()
        else:
            log.warning("Gemini stream produced no text")
            yield "క్షమించండి, మళ్ళీ చెప్పండి?"
    except Exception as e:
        log.error("Gemini stream failed: %s", e)
        cb.gemini_breaker.record_failure()
        if not emitted_any:
            yield "క్షమించండి, technical issue."

async def handle_widget_ws(ws: WebSocket):
    """Website widget entry point — lets a visitor on heynikki.in talk to
    Nikki directly through their browser microphone, no phone call
    needed. Reuses the exact same Session/VAD/STT/Gemini/TTS/barge-in/
    filler pipeline already built and tested for Exotel calls (this
    session, earlier today) — only the transport differs. If barge-in,
    fillers, or language switching work on the phone line, they work
    here too, for free.

    Protocol — deliberately simpler than Exotel's, since there's no
    telephony provider dictating the format:
      - Client sends raw 16-bit PCM mono @ 16kHz binary WS frames
        directly. This matches PIPE_SR exactly, so — unlike Exotel's
        8kHz, which needs upsampling — zero resampling happens on the
        input side.
      - Server sends raw 16-bit PCM mono @ 8kHz binary WS frames back
        (same audio speak_dynamic already produces for Exotel).
      - No JSON envelope, no base64, no stream_sid/call_sid — a plain
        binary audio pipe in both directions.

    Deliberately does NOT create a `calls` row or upload a recording —
    this is a public "try it now" demo surface on the marketing site,
    not a billable customer call. If widget conversations should show
    up in the dashboard/analytics later, that's a small, separate
    addition (wire up save_call_row/finalize_call_recording the same
    way handle_exotel_ws does).

    UNTESTED IN A REAL BROWSER as of this commit — the backend logic is
    tested the same way everything else today was (mocked WebSocket,
    verified message flow), but actual browser audio capture/playback
    behavior (autoplay policies, AudioContext quirks, mic permission
    flows) can only be verified by loading the widget in a real browser.
    See scripts/test_widget_local.html for a one-time manual verification
    page — run that before trusting this live on heynikki.in.
    """
    log.info("INCOMING widget WS attempt")
    await ws.accept()
    s = Session(ws)
    s.transport = "widget"
    s.started_at = time.time()
    # Same demo persona heard on the phone line — a website visitor and a
    # phone caller should get a consistent first impression of Nikki.
    s.tenant = {"name": "Hey Nikki", "voice_profile": DEFAULT_VOICE}
    s._sys = SYSTEM_PROMPT.format(business_type="general", business_name="Hey Nikki")
    log.info("widget WS accepted")

    asyncio.create_task(s.play_cached("default"))

    try:
        while True:
            pcm_16k = await ws.receive_bytes()
            if not pcm_16k:
                continue
            utt = s.feed_caller_audio(pcm_16k)
            if utt is not None:
                asyncio.create_task(_handle_utterance(s, utt))
    except WebSocketDisconnect:
        log.info("widget ws disconnect")
    except RuntimeError as e:
        if "not connected" in str(e) or "after sending" in str(e):
            log.info("widget ws closed: %s", e)
        else:
            log.exception("widget runtime: %s", e)
    except Exception as e:
        log.exception("widget handler: %s", e)
    finally:
        s.socket_open = False
